### ISSUE TITLE
Can't use ember-websockets as an addon dependency.

### ISSUE THREAD

**Issue by Vazgen7788** [thoov/ember-websockets#105]
I want to create new addon which will depend on ```ember-websockets``` addon. Here are steps which I tried.

1. Create new addon ```ember-example-addon``` .
2. Install ```ember-websockets``` addon in ```ember-example-addon``` with current command
```sh
$ ember install ember-websockets
```
3. Move ```"ember-websockets": "6.1.0"``` from **devDependencies** to **dependencies** in ```ember-example-addon``` .

Want to compile  ```ember-example-addon``` it trows npm error.
`````
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/vazgen/tmp/ember-addon-with-websocket/tmp/source_map_concat-input_base_path-f0BcKngS.tmp/0/undefined/urijs/src/URI.min.js'
``````
**The reason is that In** ```ember-websockets``` **index.js**  "_included_ " **function's** app.bowerDirectory **gives undefined**.

Cant find solution. Can anyone help me.

**Comment by thoov** [comment]
Thanks for reporting this issue @Vazgen7788. Let me take a look into this

**Comment by thoov** [comment]
Can you try with ember-websockets@6.2.0 and see if that works for you?

**Comment by Vazgen7788** [comment]
Thanks very much for help @thoov . It fixed partly. I'm working in local environment and installing my addon to  ember application using ```npm link``` . Here are what happens ...

1.  Init new ember addon
```sh
$ ember addon addon-with-ember-websockets
````
2 Install ember-websockets  in ```addon-with-ember-websockets```
```sh
$ ember install ember-websockets
```
3. Move ```ember-websockets``` from **devDependencies** to **dependencies**  .
4. Make ```addon-with-ember-websockets``` available in local.
```sh
$ npm link
```
5. Install  ```addon-with-ember-websockets``` to ```my-ember-app```
```sh
$ npm link addon-with-ember-websockets
```
6. add ```addon-with-ember-websockets```  to ```my-ember-app``` package.json as devDependency.
7. run ```ember s``` in ```my-ember-app``` trows error.

It compiles  when I install urijs and mock-socket in application.

**Comment by Vazgen7788** [comment]
I found the solution for my case. I can download and modify ember-websockets addon . And generally my addon will depend on ember-websockets.. :) Thank you again for help.

**Comment by Vazgen7788** [comment]
Thank you very much. Now everything is ok.
