### ISSUE TITLE
Uncaught ReferenceError: io is not defined

### ISSUE THREAD

**Issue by Schnodderbalken** [thoov/ember-websockets#111]
I had ember-websockets running, everything was fine. Then I wanted to run my ember application on another device. There I got the following error in the browser:

`socket-io.js:12 Uncaught ReferenceError: io is not defined
    at Class.createSocket (http://localhost:4200/assets/vendor.js:85187:25)
    at Class.socketFor (http://localhost:4200/assets/vendor.js:85253:31)
...`

In the line
` var newSocketIO = io(url, options);`

I was wondering why it worked on my initial device. So I removed the node_modules folder and then it occurred there as well.

When I enter `ember install ember-websockets` 
I get
`Installed packages for tooling via npm.
installing ember-websockets
  install package mock-socket
Installed packages for tooling via npm.
  install bower package urijs
  cached https://github.com/LearnBoost/socket.io-client.git#1.7.1
  cached https://github.com/medialize/URI.js.git#1.18.3
Installed browser packages via Bower.
Installed addon package.`

`ember g socket-io`

returns

`installing socket-io
  install bower package socket.io-client
  cached https://github.com/medialize/URI.js.git#1.18.3
  cached https://github.com/LearnBoost/socket.io-client.git#1.7.1`

So it seems that everything is installed properly.

I would have thought that ember-websocket takes care of resolving the dependency to socket-io itself so that I don't have to do something manually. What do I have to do in order to resolve that issue?

**Comment by thoov** [comment]
Thanks @Schnodderbalken for opening this issue. The socket.io-client library which ember-websockets uses was updated and the location of the file was changed without my knowledge. I have a PR (#116) which will hopefully fix this and will push a new version out once its merged.

**Comment by thoov** [comment]
Can you try version 6.2.1 and see if that fixes your issue?

**Comment by Schnodderbalken** [comment]
Well, somehow I still get the above mentioned error. I changed the package.json entry to `"ember-websockets": "6.2.1"`. I removed all cached npm and bower modules and re-installed them. Still no success :-(

**Comment by thoov** [comment]
@Schnodderbalken My fix in #116 included the wrong path (my mistake). I have now fixed it in #117 and push a release 6.2.2. I verified that io was found so this issue should now be fixed. Can you check one last time. Thanks!

**Comment by Schnodderbalken** [comment]
Now it works. Thanks for your quick reaction :) 👍
