### ISSUE TITLE
Uncaught ReferenceError: io is not defined

### ISSUE THREAD

**Issue by maheshiv** [thoov/ember-websockets#119]
I am using ember-websockets v4, mock-socket v3 in my application. I am able to connect to the socket(in server) successfully from other applications. When I used ember-sockets, I am getting `io is not defined` error.
Stack error,
Inside services/socket-io.js file
```
createSocket: function createSocket(url) {
      var options = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

      var newSocketIO = io(url, options);
      newSocketIO.connect();
      return newSocketIO;
    },

**Comment by thoov** [comment]
Hi @maheshiv. Sorry you are running in this error. Are you able to upgrade ember-websockets to v6.2.2? I have fixed a similar issue (https://github.com/thoov/ember-websockets/issues/111) and release the fix for it in that version

**Comment by jstoup111** [comment]
I had 6.3.0 and it didn't work.

**Comment by thoov** [comment]
@jstoup111 Could you run `bower install --save socket.io-client` in your project and see if that help?

**Comment by jstoup111** [comment]
I'm not sure what ended up causing the issue but it's working after I uninstalled and reinstalled.
