### ISSUE TITLE
New release for 2.6/2.17

### ISSUE THREAD

**Issue by pcambra** [thoov/ember-websockets#153]
Hi,

Would you mind making a release compatible with the new modules API, the changes that were included in:

https://github.com/thoov/ember-websockets/commit/e8481a7eacf8bab12a572ebf0b6851b2f74ac751

Otherwise when using 2.16/2.17, it needs to be included this way

```
"ember-websockets": "git+https://github.com/thoov/ember-websockets.git#bc002a7",
```

Thanks

**Comment by thoov** [comment]
@pcambra Thanks for the issue. I published a new release (7.1.0). Can you try it out and let me know if it helps you out.

**Comment by pcambra** [comment]
```bash-4.2# $(npm bin)/ember install ember-websockets --save
npm: Installed ember-websockets
Installed addon package.
bash-4.2# cat package.json | grep websockets
    "ember-websockets": "^7.1.0",```

🎉 🎉 🎉

**Comment by pcambra** [comment]
Can confirm that 7.1.1 handles this issue
