### ISSUE TITLE
Wrap sockets with Promise object.

### ISSUE THREAD

**Issue by yratanov** [thoov/ember-websockets#16]
Current behavior: 
1) User needs to emit some changes to the socket.
2) The socket is not connected yet (`readyState == CONNECTING`)
3) `emit` action does nothing.

Expected behavior.
1) User needs to emit some changes to the socket.
2) The socket wrapped with Promise. Socket state is `CONNECTING`
3) `emit` action binds send to promise's resolve handler.

Example (in coffee):

``` coffee
socketPromise = new Ember.RSVP.Promise (resolve, reject) ->
      websocket = new WebSocket(socketURL)
      websocket.onopen -> resolve(websocket)
      websocket.onerror (error)-> reject(error)

socketPromise.then (socket)=>
  socket.send(data)
```

With this approach we can be sure that our message will be sent, even if we proceed `emit` before connection actually opened.

What do you think?

UPD: I know, we can use `onopen` action, but I believe ember-way it to use promises (same way it did in DS)

**Comment by ryanbillingsley** [comment]
I agree with @yratanov that using promises would be a lot easier to use and feel more in line with the rest of Ember

**Comment by vitalets** [comment]
Maybe it would be reasonable to take this promise-based websocket wrapper: https://github.com/vitalets/websocket-as-promised
