### ISSUE TITLE
ReferenceError: io is not defined

### ISSUE THREAD

**Issue by amiarSlimane** [thoov/ember-websockets#172]
```
 createSocket(url, options = {}) {
      const newSocketIO = io(url, options);
      newSocketIO.connect();
      return newSocketIO;
    },

```
```
ember-cli: 3.17.0
node: 13.13.0
```

it works in a new empty project, but the one i working on , does not work, the same ember version, 
i think other dependencies causing this issue

**Comment by gabrielcsapo** [comment]
same issue here :(

**Comment by gabrielcsapo** [comment]
I fixed the issue by using socket.io-client and ember-auto-import instead of this library @amiarSlimane

**Comment by mpanic** [comment]
Same error happens for me when I use `ember-websockets` v 8.0
If I switch back to v 7.2.0 everything works fine. 
What changed in the 8.0 release?

**Comment by jcardali** [comment]
I am experiencing the same issue upgrading from 7.2.0 to 8.0.0.

To me it seems most likely that the break may have been introduced [here](https://github.com/thoov/ember-websockets/pull/190/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L33-L79), though it looks like a noop to me.

@thoov Any thoughts?

**Comment by progand** [comment]
Downgrading to 7.2.0 fixes the issue for me
