### ISSUE TITLE
Does this only work with websocket protocol?

### ISSUE THREAD

**Issue by Jordan4jc** [thoov/ember-websockets#26]
I've been having troubles getting socket.io to work with this addon, is it because my server is not using the ws protocol?

**Comment by thoov** [comment]
Yes, currently this is only for ws supported backends which socket.io is not. I recommend using [ws](https://www.npmjs.com/package/ws) which is a ws protocol supported node library. I plan to look into supporting [socket.io](https://github.com/thoov/ember-websockets/issues/23) in the future. I know of this [project](https://github.com/Wildhoney/EmberSockets) but I have never personally used it so I do know much about it.
