### ISSUE TITLE
reconnect

### ISSUE THREAD

**Issue by sebyx07** [thoov/ember-websockets#28]
is there a way to retry reconnection ?

**Comment by thoov** [comment]
@sebyx07 right now there is not a clean way of doing that. In my upcoming pull request (https://github.com/thoov/ember-websockets/pull/27) there will be support for that

**Comment by thoov** [comment]
@sebyx07 I have merged my PR and it has recconnect support. You can see it here: https://github.com/thoov/ember-websockets#reconnecting
