### ISSUE TITLE
The `ember generate` command failed on installation

### ISSUE THREAD

**Issue by HT808s** [thoov/ember-websockets#30]
### When I execute "ember install ember-websockets" on my brand new ember-cli application, my output is the following

version: 0.2.3
0.2.3

Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  not-cached git://github.com/medialize/URI.js.git#*
  resolved git://github.com/medialize/URI.js.git#1.15.0
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Am I doing something wrong ?**

**Comment by thoov** [comment]
@HT808s thanks for creating an issue about this and I am noticing this too. It looks like everything is working correctly even though the error is appearing. I will be looking into this tonight/tomorrow and see if I can get rid of the error.

**Comment by HT808s** [comment]
Glad i coul help.
By the way the addon is working just fine !

**Comment by thoov** [comment]
This issue seems to be with ember-cli: https://github.com/ember-cli/ember-cli/issues/3831& https://github.com/ember-cli/ember-cli/pull/3846. I believe this issue will be resolved once it is fixed in ember-cli
