### ISSUE TITLE
InvalidStateError when closing and reconnecting 

### ISSUE THREAD

**Issue by Alimero** [thoov/ember-websockets#39]
Hi,

i get the following Error in Webbrowser when trying to reconnect or retriev a new websocket, after the old websocket gets closed (by the websocket client itself or the websocket server): 

**"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"**

Here is an example. My websocket client is build like the example in the readme. Additionally i have a click-event, that sends a message to my websocket server. When the connection gets close, for example by the websocket server (cause of uncought error), and i try to reconnect or retriev a new websocket, i get the above error. 
Curious is, that every time i fire the click-event (after retrieving a new websocket connection), my websocket server register a new user-session (connect) but no incoming message.  

Can somebody help me?

**Comment by thoov** [comment]
@Alimero I can help you out. Could you post some of your code so I can test it on my end?

**Comment by Alimero** [comment]
@thoov Thanks. Here is the code.

    export default Ember.Controller.extend({  
        socketService: Ember.inject.service('websockets'),
         init: function() {
            this._super.apply(this, arguments);
            var socket = this.get('socketService').socketFor(this.uri);
            socket.on('open', this.openHandler, this);
            socket.on('close', this.closeHandler, this);
            socket.on('error', this.errorHandler, this);
            socket.on('message', this.messageHandler, this);
        },
        openHandler: function(event) {
            console.log('Open websocket.');
        },   
        closeHandler: function(event) {
            console.log('Close websocket.' ) ;
            if(event.code !== 1000){
                this.set('refreshPage', true);
            }    
         },
         actions:{
            requestFile: function(filename) {         
                var node = this.model;  
                var socket = this.get('socketService').socketFor(this.uri);
                var json = {
                    'filename': filename.get('name')
                };
                socket.send(json, true);
                //tried also


        }

**Comment by thoov** [comment]
If you update to the latest version (1.2.1) you will have this method to retrieve the readyState:

```js
var socket = this.get('socketService').socketFor(this.uri);
socket.readyState();
```

I created a simple node server that had a websocket app running on it. Below is the code I modified from you:

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  uri: 'ws://localhost:8882',
  socketService: Ember.inject.service('websockets'),

  init: function() {
    this._super.apply(this, arguments);
    var socket = this.get('socketService').socketFor(this.uri);
    socket.on('open', this.openHandler, this);
    socket.on('close', this.closeHandler, this);
    socket.on('error', this.errorHandler, this);
    socket.on('message', this.messageHandler, this);
  },
  openHandler: function() {
    console.log('Open method called');
  },
  errorHandler: function() {
    console.log('Error method called');
  },
  messageHandler: function() {
    console.log('Message method called');
  },
  closeHandler: function() {
    console.log('Close method called');

    // try and reconnect every 2 seconds
    Ember.run.later(this, function() {
      this.get('socketService').socketFor('ws://localhost:8882').reconnect();
    }, 2000);
  },
  actions: {
    requestFile: function(filename) {
      var socket = this.get('socketService').socketFor('ws://localhost:8882');

      if(socket.readyState() === WebSocket.OPEN) {
        var json = {
          'filename': filename
        };
        socket.send(json, true);
      }
    }
  }
});
```

To test the reconnecting case I would kill my node server and it would cause the `closeHandler` to be called. I would then bring my node server back up and it was able to reconnect and then I was able to send the messages back to the server. Can you let me know if you are able to have this code run for you?

**Comment by Alimero** [comment]
I upgraded to 1.2.1 and added the above changes. It works. Thanks a lot!!
