### ISSUE TITLE
socketFor function does not allow for protocol parameter

### ISSUE THREAD

**Issue by Dynasty9** [thoov/ember-websockets#40]
It's impossible to specify a protocol to connect to as per the websocket api passing Websocket(url, protocol).

**Comment by thoov** [comment]
@Dynasty9 Thanks for bringing this up. I will add that shortly.

**Comment by thoov** [comment]
@Dynasty9 If you download version 1.2.0 it will include my changes. You should now be able to do:

```js
var socket = this.get('socketService').socketFor('ws://localhost:7000/', ['myOptionalProtocol']);
```

Let me know if this works for you

**Comment by Dynasty9** [comment]
Thanks thoov, checking it out now

**Comment by Dynasty9** [comment]
Works great! :+1:
