### ISSUE TITLE
Feature Request: DS adapter

### ISSUE THREAD

**Issue by DragorWW** [thoov/ember-websockets#45]
I writeing for my project websocket adapter. If need, i will can make pullRequest for this project.

**Comment by dowsanjack** [comment]
@DragorWW would be great if you can share that adapter here on point to your repo. Thanks!

**Comment by saerdnaer** [comment]
@DragorWW Any updates to on you websocket DS adapater project?

**Comment by Schnodderbalken** [comment]
I started something basic for socket.io based on another gist. Maybe you guys can use it? https://gist.github.com/Schnodderbalken/40114a2e500ae27864c6b4ae9688d3f2
