### ISSUE TITLE
websocket not open / connection

### ISSUE THREAD

**Issue by sma202** [thoov/ember-websockets#56]
I'm getting an exception on ember 2.2.0 when using the simple hello word example:

Uncaught Error: Assertion Failed: Cannot send message to the websocket while it is not open.

If I put a breakpoint on line 69 websocket-proxy.js then it works ok, otherwise it thinks the websocket is not open and will throw the assert.  This leads me to believe it is some kind of timing issue / race condition where the socket is not being retrieved from the cache properly:

_ember['default'].assert('Cannot send message to the websocket while it is not open.', this.readyState() === WebSocket.OPEN);

**Comment by thoov** [comment]
@sma202 Thanks for finding this. I am looking into it now

**Comment by thoov** [comment]
@sma202 could you post your controller or component so I can reproduce it on my side?

**Comment by sma202** [comment]
import Ember from 'ember';

export default Ember.Controller.extend({
  /*
  * 1) First step you need to do is inject the websocket service into your object. You
  * can inject the service into component, controllers, object, mixins, routes, and views.
  */
  websockets: Ember.inject.service('websockets'),
 
  init: function() {
    this._super.apply(this, arguments);
 
    /*
    * 2) The next step you need to do is to create your actual websocket. Calling socketFor
    * will retrieve a cached websocket if one exists or in this case it
    * will create a new one for us.
    */
    var socket = this.get('websockets').socketFor('ws://host:7200', ['echo-protocol']);
 
    /*
    * 3) The final step is to define your event handlers. All event handlers
    * are added via the `on` method and take 3 arguments: event name, callback
    * function, and the context in which to invoke the callback. All 3 arguments
    * are required.
    */
    socket.on('open', this.myOpenHandler, this);
    socket.on('message', this.myMessageHandler, this);
    socket.on('close', function(event) {
      // anonymous functions work as well 
	   console.log('socket closed');
    }, this);
  },
 
  myOpenHandler: function(event) {
    console.log('On open event has been called: ' + event);
  },
 
  myMessageHandler: function(event) {
    console.log('Message: ' + event.data);
  },
 
  actions: {
    sendButtonPressed: function() {
      /*
      * If you need to retrieve your websocket from another function or method you can simply
      * get the cached version at no penalty
      */
	  console.log('socket1: ' + socket);
      var socket = this.get('websockets').socketFor('ws://NJ1-FT23Q22-D:7200', ['echo-protocol']);
	  console.log('socket2: ' + socket);
	  console.log('socket2: ' + socket.readyState());
      socket.send('Hello Websocket World');
    }
  },
  
  willDestroy() {
    this.get('websockets').closeSocketFor('ws://host:7200');
  }
  
});

**Comment by d2rk** [comment]
+1

Just checked `socket.readyState()` before doing `send` and it returned `1`. However, once `send` has been called you get `assert`.

**Comment by thoov** [comment]
@sma202 @d2rk, I am not able to reproduce this issue. I tested with this code below on both Ember 2.2 & 2.3:

```js
// node server.js
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({ port: 8888 });

wss.on('connection', function connection(ws) {

  ws.on('message', function incoming(message) {
    console.log('Message Recieved');
    ws.send('message-recieved');
  });

  console.log('Connection Occurred');
  ws.send('connection-occurred');
});
```

```js
// index.js
import Ember from 'ember';

export default Ember.Controller.extend({
  websockets: Ember.inject.service('websockets'),

  init: function() {
    this._super.apply(this, arguments);

    var socket = this.get('websockets').socketFor('ws://localhost:8888', ['echo-protocol']);

    socket.on('open', this.myOpenHandler, this);
    socket.on('message', this.myMessageHandler, this);
  },

  myOpenHandler: function(event) {
    console.log('On open event has been called: ' + event);
  },

  myMessageHandler: function(event) {
    console.log('Message: ' + event.data);
  },

  actions: {
    sendButtonPressed: function() {
      var socket = this.get('websockets').socketFor('ws://localhost:8888', ['echo-protocol']);
      console.log('socket2: ' + socket);
      console.log('socket2: ' + socket.readyState());
      socket.send('Hello Websocket World');
    }
  }
});
```

Can you try the above code and see if you are still getting the error?

**Comment by jatt** [comment]
I have the same error, whenever I invoke `socket.send('msg')` I get error, while in the same time `socket.socket.send('msg')` succeeds. 

Possible cause is that assert checks `this.readyState() === WebSocket.OPEN`, and according to Chrome console, `this.readyState() => 1` while `WebSocket.OPEN => function dispatchEvent() { [native code] }`

**Comment by thoov** [comment]
I am still not able to see this issue. Can you provide your controller, template, and server code so I can run it locally?

**Comment by jatt** [comment]
I just checked, if I open console in any random page, `WebSocket.OPEN` is `1`, but if I open console in my Ember CLI app, it is some function. Seems that something redefines it, so it doesn't look like an ember-websockets problem. This issue can be closed since it's not a bug, but I'll post a solution here once I find it.

**Comment by jatt** [comment]
I did some debugging, and meet the nice guy who substitutes `window.WebSocket` with own stuff: https://github.com/HubSpot/pace. Case closed.

**Comment by acorncom** [comment]
@jatt can this issue be closed?

**Comment by jatt** [comment]
I think so. Even if there is unexpected behavior, ember-websockets is not at fault. For future reference, fix is to disable Pace for Websocket connections.
