### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by jatt** [thoov/ember-websockets#57]
I've forked the repo and tried to run tests, but I failed. Steps to reproduce:

1. Clone a fresh master
2. Run `npm install`
3. Run `bower install` (btw, this one is missing in README)

Result:

1. `ember t` gets stuck forever
2. `ember s` gives error "Ember Views require jQuery between 1.7 and 2.1" (while `jQuery.fn.jquery => "1.12.0"`)

I also noticed that `ember-cli` and `ember` versions are not the most recent ones, so I suspect that there is some disagreement between dependency versions somewhere. If you have some idea what can cause this problem, it would be very nice if you could fix that, since such changes are better made by someone who knows the app. If you have no idea and/or no time to take care of it, please let me know, I'll dig this one on my own.

**Comment by thoov** [comment]
@jatt Thanks for opening up the issue. I updated the readme to include the bower install and upgrade the project to the latest version of ember-cli (1.13.14). 

I followed your steps but was not able to see your error. Can you try again with a new clone? Also can you let me know which version of node and environment you are using?

**Comment by jatt** [comment]
Many thanks for the update, I tried another clone and everything works now. I also tried `npm test` previous time, and just noticed that it resolves to `ember try:testall` instead of `ember t`, maybe it could break my environment.

**Comment by thoov** [comment]
@jatt Im glad its now working for you. Generally npm test is only used for travisCI as it is an easy way to test against the different environments (release, beta, canary) and ember test is better suited for day to day dev work. I would suggest just running ember test and not npm test unless you see travisCI failed.
