### ISSUE TITLE
'.' character in url causing Ember.set error in 2.3

### ISSUE THREAD

**Issue by mmitchellgarcia** [thoov/ember-websockets#63]
Hey guys, really awesome add-on. I'm having issues getting it set up though. 

It looks like because Ember now supports nested getters/setters with '.' notation, the socketFor() function breaks when it tries to add the newly created SocketIOProxy to the cache. Here's the exact error:

`Property set failed: object in path "sockets.http://uniteable" could not be found or was destroyed. Error: Property set failed: object in path "sockets.http://uniteable" could not be found or was destroyed.`

Version info:

```
DEBUG: Ember             : 2.3.0+667a2a6b
DEBUG: jQuery            : 1.11.3
DEBUG: Ember Simple Auth : 1.0.0
```

Super understand that this package wasn't built for 2.3, but wanted to get some advice on working through this. 

Do you think it'd efficient to rewrite the socketFor function to allow you to add your own namespace? Like this.socketFor(socketUrl, 'api:pusher'), instead of automatically adding it? Would love some input - I can create a push request for the custom namespaces functionality if you're interested. Thanks.

**Comment by thoov** [comment]
@mmitchellgarcia Thanks for finding this. What is the url that you are passing to socketFor?

**Comment by mmitchellgarcia** [comment]
It is: "http://uniteable.com:3000"

**Comment by thoov** [comment]
@mmitchellgarcia I just merged a fix for this. Can you try version 2.0.2 and see if that works for you?

**Comment by mmitchellgarcia** [comment]
@thoov Works - thank you!
