### ISSUE TITLE
This addon does not work if used within other addons

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [thoov/ember-websockets#66]
Usually it throws app.import is not a function error

See here the generic problem and solution
https://github.com/ember-cli/ember-cli/issues/3718 

It would be nice to have it fixed soon

**Comment by thoov** [comment]
Thanks for opening this issue @andriy-zhelvachenko. Would you be able to provide a PR for the fix?

**Comment by andriy-zhelvachenko** [comment]
PR=?

**Comment by andriy-zhelvachenko** [comment]
You probably meant "pull request", i.e. patch, right?

**Comment by thoov** [comment]
@andriy-zhelvachenko Sorry for the delay in getting back to you. Yes, by "PR" I meant pull request

**Comment by jamesdixon** [comment]
@andriy-zhelvachenko works fine for me. just installed on ember 2.3 using ember cli 2.3

**Comment by acorncom** [comment]
@andriy-zhelvachenko can this issue be closed?

**Comment by BryanCrotaz** [comment]
I've just provided a PR fix for this

**Comment by GavinJoyce** [comment]
@andriy-zhelvachenko if you include the following in the app config it should work:

`
'ember-websockets': {
   socketIO: true
 },
`

Here's [the check](https://github.com/thoov/ember-websockets/blob/849c642f011826f3d3a668e1a599c461da690cc1/index.js#L19-L21) in source
