### ISSUE TITLE
socketFor() sometimes returns WebSocket instead SocketProxy

### ISSUE THREAD

**Issue by kunerd** [thoov/ember-websockets#68]
To reproduce open a socket connection and set your computer offline (e.g. by using offline mode in Firefox). Now call `socketFor()` again and it returns the plain `WebSocket` object instead of the proxy object.

**Comment by thoov** [comment]
@kunerd Thanks for finding this. I believe I have a fix for this. I will let you know once I push the fix to npm so you can test it.
