### ISSUE TITLE
passing authorization token

### ISSUE THREAD

**Issue by jamesdixon** [thoov/ember-websockets#70]
Hi,

Is there a recommended way to be able to pass an authorization token along with every request?

Thanks!
James

**Comment by thoov** [comment]
Hi @jamesdixon 

Off of the top of my head you could do something like this:

```js
import Ember from 'ember';

function authSend(socket, messageObject) {
  socket.send({authToken: 'my-auth-token', ...messageObject}, true);
}

export default Ember.Component.extend({
  socketService: Ember.inject.service('websockets'),
  
  actions: {
    buttonPressed() {
      var socket = this.get('socketService').socketFor('ws://localhost:7000/');
      authSend(socket, { foo: 'bar' });
    }
  }
});
```

Basically create a wrapper function that you call instead of directly calling the send method. This way every time you call `authSend` a token can be added to the payload. Let me know if this helps.

**Comment by jamesdixon** [comment]
Thanks, @thoov. I'll give it a shot!

**Comment by acorncom** [comment]
@jamesdixon can this issue be closed?

**Comment by jamesdixon** [comment]
I believe it can. It's been a while, but if I'll reopen if I need to. Thanks!
