### ISSUE TITLE
socket.reconnect is not a function

### ISSUE THREAD

**Issue by nanoart** [thoov/ember-websockets#72]
Hi, 

I am trying your ember-websockets, and using the reconnect example on https://github.com/thoov/ember-websockets. However I got "socket.reconnect is not a function" when running.

Many thanks,

Mike

Here is the piece of the code,

```
myCloseHandler: function myCloseHandler(event) {
  console.log('On close event has been called: ' + event);
  var socket = this.get('socketService').socketFor('wss://sense.hellomy.com/ws');
  _ember['default'].run.later(this, function () {
    //reconnect every two seconds;
    socket.reconnect();
  }, 2000);
}, 
```

**Comment by mmitchellgarcia** [comment]
Hey @nanoart - it looks like you need to include the socket in the [run.later function as an argument](http://emberjs.com/api/classes/Ember.run.html#method_later). I believe run.later requires you specify the context. Try this:

```
myCloseHandler: function myCloseHandler(event) {
  console.log('On close event has been called: ' + event);
  var socket = this.get('socketService').socketFor('wss://sense.hellomy.com/ws');
    run.later(this, function(socket) {
      socket.socket.io.reconnect();
    }, socket, 2000);
}, 
```

**Comment by acorncom** [comment]
@nanoart can this issue be closed?

**Comment by doughsay** [comment]
I don't think so. `socket.socket.io.reconnect();` is reaching into socket.io internals.  The API described in this addon is: `this.get("myService").socketFor(sockerUrl).reconnect();`.  This function does not exist like the README implies that it does.

**Comment by doughsay** [comment]
Just looked into it more closely.  The `reconnect` function is defined for the websocket proxy but NOT for the socket.io proxy.  Can we get this fixed @thoov?
