### ISSUE TITLE
Bug: Incorrect OFF on socket.io events

### ISSUE THREAD

**Issue by urbany** [thoov/ember-websockets#73]
Hi, first of all thank you for the addon.
I noticed there is a bug on the socket.io proxy OFF method. On line: https://github.com/thoov/ember-websockets/blob/master/addon/helpers/socketio-proxy.js#L38
The correct way to check the socket.io url is `this.socket.io.uri` instead of `this.socket.io.url`:
```js
const listeners = this.listeners.filter(listener => listener.callback === callback && listener.url === this.socket.io.url && listener.type === type);
```
Should be:
```js
const listeners = this.listeners.filter(listener => listener.callback === callback && listener.url === this.socket.io.uri && listener.type === type);
```

PS: On line https://github.com/thoov/ember-websockets/blob/master/addon/helpers/socketio-proxy.js#L32 you are checking it correctly.

**Comment by thoov** [comment]
Thanks for finding this @urbany! I will update shortly
