### ISSUE TITLE
Attempting to watch missing directory: node_modules/mock-socket/src

### ISSUE THREAD

**Issue by sepetukas** [thoov/ember-websockets#75]
Just installed ember-websockets 4.0.0 and got this error 'Attempting to watch missing directory: node_modules/mock-socket/src'
 Any ideas how to solve it?

**Comment by thoov** [comment]
@sepetukas thanks for finding this. Let me investigate

**Comment by thoov** [comment]
@sepetukas Can you uninstall 4.0.0 and install 4.0.1 and see if that fixes your problem

**Comment by sepetukas** [comment]
This fixed everything of course. Thx

**Comment by thoov** [comment]
perfect. thanks for finding
