### ISSUE TITLE
Attempting to inject an unknown injection: `service:socket-io`

### ISSUE THREAD

**Issue by Schnodderbalken** [thoov/ember-websockets#79]
I did exactly as it is told in https://github.com/thoov/ember-websockets/blob/master/docs/socket-io.md

In fact, my controller looks like this:

```
"use strict";

import Ember from 'ember';

export default Ember.Controller.extend({

  	socketIOService: Ember.inject.service('socket-io'),

    init: function() {
    	this._super.apply(this, arguments);
		var socket = this.get('socketIOService').socketFor('http://localhost:5000/');
	}
});
```

When I open the corresponding route the console output is as follows:

Attempting to inject an unknown injection: `service:socket-io`

Using ember 2.7.0

**Comment by thoov** [comment]
Thanks for opening the issue @Schnodderbalken. I just tested against a blank app and everything seems to work fine. Did you run `ember g socket-io` and if so what was the output?

**Comment by Schnodderbalken** [comment]
Thank you for the quick response. Yes, I ran the command which resulted in the following output:
```
installing socket-io
  install bower package socket.io-client
  not-cached https://github.com/LearnBoost/socket.io-client.git#*
  resolved https://github.com/LearnBoost/socket.io-client.git#1.4.8
Installed browser packages via Bower.
```

**Comment by thoov** [comment]
Both of those seem correct. This is strange.  Which version of ember-cli / node / npm are you using?

**Comment by Schnodderbalken** [comment]
```
$ ember --version
ember-cli: 2.7.0
node: 0.12.2
os: darwin x64

$ npm --version
3.5.2
```

**Comment by thoov** [comment]
I ran the setup on 0.12 and everything worked. Can you try 2 things. One, delete ember-websockets from node_modules and try running `ember install ember-websockets` & `ember g socket-io` again. Two, create a blank project via `ember new foobar` and run `ember install ember-websockets` & `ember g socket-io` inside that. I want to see if it is specific to your project. I will check back on this when i wake up. THanks!

**Comment by Schnodderbalken** [comment]
I deleted the ember-websockets folder in node_modules.
Then i executed `ember install ember-websockets`.

Output was:

```
Missing npm packages: 
Package: ember-websockets
  * Specified: 4.0.1
  * Installed: (not installed)

Run `npm install` to install missing dependencies.
```

So i executed `npm install`
Many things were successfully installed. I eventually ran `ember install ember-websockets` again

Output:

```Installed packages for tooling via npm.
installing ember-websockets
  install package mock-socket
Installed packages for tooling via npm.
  install bower package urijs
  cached https://github.com/medialize/URI.js.git#1.18.1
Installed browser packages via Bower.
Installed addon package.```

The issue I described above still happened so as you suggested I created a new ember project executing the following commands:
`ember new ember-test`
`ember g route test`
`ember g controller test`
`ember install ember-websockets`
`ember g socket-io`

I follow the tutorial https://github.com/thoov/ember-websockets/blob/master/docs/socket-io.md again. I don't know why but this time I did not get the error I got previously. Instead it said this:

```ReferenceError: io is not defined
    at createSocket (socket-io.js:12)
    at socketFor (websockets.js:55)
    at init (test.js:15)
    at superWrapper [as init] (ember.debug.js:25371)
    at new Class (ember.debug.js:38083)
    at Function.ClassMixinProps.create (ember.debug.js:38354)
    at instantiate (ember.debug.js:1498)
    at lookup (ember.debug.js:1336)
    at Object.Container.lookup (ember.debug.js:1255)
    at exports.default._emberMetalMixin.Mixin.create.lookup (ember.debug.js:34530)```

It would be great to know how I get rid of the error happening in the previous project as well as this new error :). Very strange.

**Comment by Schnodderbalken** [comment]
Okay now things get totally strange. After I stopped the new ember server and restarted the old one where I got the error stated above everything worked fine.
I should have tried just restarting the ember server. Seems to have anything to do with my local setup. Sorry for bothering you.

**Comment by thoov** [comment]
@Schnodderbalken no worries. Glad you figured it out.
