### ISSUE TITLE
Add compatibility with FastBoot

### ISSUE THREAD

**Issue by steveszc** [thoov/ember-websockets#83]
Socket.io client is causing issues in FastBoot due to direct usage of the Navigator object. There may be other issues that need to be resolved too.

Add-on will need to be updated according to the advice here: http://ember-fastboot.com/docs/addon-author-guide

**Comment by steveszc** [comment]
@thoov When do you expect to cut a new release that includes #84?

**Comment by thoov** [comment]
@steveszc Let me cut it right now. I will comment on this once its done.

**Comment by thoov** [comment]
Just published. Version 6.0.0 should have your changes

**Comment by steveszc** [comment]
Awesome, thanks. I see the 6.0 release on NPM but not in the GitHub releases... is that expected?

**Comment by thoov** [comment]
Ya that is expected. It shouldn't impact downloading from NPM
