### ISSUE TITLE
Unexpected behavior when using emit() with four arguments

### ISSUE THREAD

**Issue by sgmurphy** [thoov/ember-websockets#85]
The socket.io `socket.emit()` method accepts an [arbitrary number of arguments](https://github.com/socketio/socket.io-client/blob/master/lib/socket.js#L140).

Ember-websockets should support the same functionality, and in most cases it does. However, when four arguments are passed to `SocketIOProxy.emit()` the method [assumes the third argument is a function and the fourth is the context](https://github.com/thoov/ember-websockets/blob/master/addon/helpers/socketio-proxy.js#L52). This means calling `SocketIOProxy.emit()` with four arguments, but without an acknowledgement function and context will not work. 😞

**Comment by thoov** [comment]
@sgmurphy Thanks for finding this. Let me fix it later today

**Comment by thoov** [comment]
@sgmurphy Can you try installing version 5.0.0 and see if that solves your issue?

**Comment by sgmurphy** [comment]
That fixed it, thanks! 👍
