### ISSUE TITLE
duplicated events when using {{input}}

### ISSUE THREAD

**Issue by benjcalderon** [thoov/ember-websockets#88]
When I call `socket.send` and in the action I'm using values from `{{input}}` I receive duplicated messages from the server.

But if, in the action, I get the values using JQuery it works as expected.
See test app [here](https://github.com/benjcalderon/ws-test/commit/6209ef3b954e52e9362e9e438040808721bcc32f)

**Comment by jasonmit** [comment]
@benjcalderon in the example code, you likely don't want to subscribe w/ `didRender`.  This gets called each time a render happens which won't map 1-1 with `willDestroyElement` so you keep setting up new subscribers every time the component renders.

Try using `didInsertElement` here instead, or not load your data via a component.  Perhaps README should be updated to reflect setting up a socket connection in a Route lifecycle hook instead.

**Comment by benjcalderon** [comment]
@jasonmit you are a lifesaver!! yep, it works perfectly with `didInsertElement`. I'll submit a PR with an updated README. Thanks a lot!
